'use strict';

// tests for create
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('create', '/todos/create.js', 'create');

describe('create', () => {
  before((done) => {
    done();
  });

  it('Test for empty request', () => {
    return wrapped.run({}).then((response) => {
      expect(response.body).equal('Empty request');
    });
  });

  it('Test for empty body', () => {
    return wrapped.run({body: ''}).then((response) => {
      expect(response.body).equal('Empty request');
    });
  });

  it('Test for Validation Errored', () => {
    return wrapped.run({body: '{ "text": 1123 }'}).then((response) => {
      expect(response.body).equal('Couldn\'t create the todo item.');
    });
  });

  it('Test for Validation Errored', () => {
    return wrapped.run({body: '{ "text": "1123" }'}).then((response) => {
      expect(response.body).equal('Couldn\'t create the todo item.');
    });
  });
});
