'use strict';

// tests for create
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('create', '/todos/create.js', 'create');

describe('create', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      console.log(response);
      // expect(response).to.not.be.empty;
    });
  });
});
